### ISSUE TITLE
Add e2e tests to the images

### ISSUE THREAD

**Issue by rmohr** [kubevirt/containerdisks#2]
Basically do the following:

```
make cluster-up
RELEASE="$(curl http://storage.googleapis.com/kubevirt-prow/devel/release/kubevirt/kubevirt/stable.txt)"
kubectl apply -f https://github.com/kubevirt/kubevirt/releases/download/${RELEASE}/kubevirt-operator.yaml
kubectl apply -f https://github.com/kubevirt/kubevirt/releases/download/${RELEASE}/kubevirt-cr.yaml
kubectl -n kubevirt wait kv kubevirt --for condition=Available
```

Then pushing one image after the other:

```
docker build . -t blub
docker push blub
```

Then create a yaml with that image and wait until `virtcl ssh` can connect to the guest.

**Comment by ksimon1** [comment]
We can reuse automation which we already have in common-templates for golden images https://github.com/kubevirt/common-templates/blob/master/dvtemplates/build_k8s_cluster.sh
It builds, pushes image into cluster and tests it with templates

**Comment by rmohr** [comment]
/reopen

we still need to adjust CI

**Comment by rmohr** [comment]
/close

CI is now also in place with https://github.com/kubevirt/project-infra/pull/2049 merged.
