### ISSUE TITLE
Support for RHEL artifacts in Containerdisks

### ISSUE THREAD

**Issue by aditi-sharma-1** [kubevirt/containerdisks#208]
This issue is being created to understand why RHEL isn't supported as an artifact in the containerdisks repository. What would be needed to add support for generating RHEL artifacts? It looks like the [common-instancetypes repository](https://github.com/kubevirt/common-instancetypes/blob/main/tests/functests/instancetype_test.go#L173) relies on containerdisks for RHEL artifacts.  

TO DO:
Discuss whether RHEL distro is needed for s390x.

**Comment by lyarwood** [comment]
@aditi-sharma-1 I believe that we didn't want to run RHEL in CI upstream in the past. We (RH) do ship RHEL containerdisks downstream however so we can provide `s390x` there if/when required.

[1] https://catalog.redhat.com/software/containers/rhel8/rhel-guest-image/601d79b5cc1405c84e0d24a4
[2] https://catalog.redhat.com/software/containers/rhel9/rhel-guest-image/6197bdceb4dcabca7fe351d5

**Comment by aditi-sharma-1** [comment]
Hi @lyarwood, Ahh okay. Could you please let me know how we can add support for s390x for rhel artifact in the downstream?

**Comment by lyarwood** [comment]
> Hi @lyarwood, Ahh okay. Could you please let me know how we can add support for s390x for rhel artifact in the downstream?

This work is being tracked by another team under the following public JIRA task https://issues.redhat.com/browse/ENGCMP-4698 

I'm going to close this issue out as we are not going to provide these containerdisks as part of this upstream project.
