### ISSUE TITLE
Seems like the quay oauth token is not referenced or injected correctly

### ISSUE THREAD

**Issue by rmohr** [kubevirt/containerdisks#32]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>

/kind bug

> /kind enhancement

**What happened**:

In the periodic https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/logs/periodic-containerdisks-push-nightly/1522033424607481856 I see:

```
CSRF token was invalid or missing.
```

As a consequence repo descriptions will not be uploaded (but publishing images continues to work).

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- KubeVirt version (use `virtctl version`):
- Kubernetes version (use `kubectl version`):
- common-templates version:
- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by 0xFelix** [comment]
The injected quay auth token was no longer valid.

It will be fixed by this PR https://github.com/kubevirt/secrets/pull/54.

**Comment by enp0s3** [comment]
@0xFelix Looks like it still failing: https://prow.ci.kubevirt.io/?job=periodic-containerdisks-push-nightly

**Comment by 0xFelix** [comment]
@enp0s3 It is fixed now

https://prow.ci.kubevirt.io/job-history/gs/kubevirt-prow/logs/periodic-containerdisks-push-nightly

**Comment by dominikholler** [comment]
@davidvossel do you have the permissions to close this issue?
