### ISSUE TITLE
Compose multi-arch image manifests for a containerdisk

### ISSUE THREAD

**Issue by jbpratt** [kubevirt/containerdisks#41]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind enhancement

Hi :smiley_cat:  

I'm curious about whether handling non-x86_64 images has been discussed yet and if it is something that is in scope/worth the time to invest. While I haven't been keeping it up the best, and it is mostly just ran by automation at this point, [we did have success with publishing](https://github.com/ContainerCraft/kmi) multi-arch image manifests (only amd64 and arm64) of the container disks we build to then boot those. Every image currently supported (and more!) within `kubevirt/containerdisks` should have a compatible aarch64 image existing for download (at least I've done it for Debian, Ubuntu, Fedora, FCOS, Centos, Rocky, and AlmaLinux).

I'm not sure how testing is currently happening of these images or if we are running these through Prow for validation, that may be even more difficult with aarch64 images if there is limited hardware.

(linking to https://github.com/kubevirt/kubevirt/issues/3558)

**Comment by rmohr** [comment]
@0xFelix FYI
