### ISSUE TITLE
periodic-containerdisks-push-nightly failing with error introspecting artifact \"centos-stream:8\": no candidates for version \"8\" and variant \"GenericCloud\" found"

### ISSUE THREAD

**Issue by lyarwood** [kubevirt/containerdisks#59]
/kind bug

**What happened**:

https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/logs/periodic-containerdisks-push-nightly/1645607628551753728

```
time="2023-04-11T02:06:49Z" level=warning msg="error introspecting artifact \"centos-stream:8\": no candidates for version \"8\" and variant \"GenericCloud\" found"
time="2023-04-11T02:06:49Z" level=error msg="artifact centos-stream:8 failed in stage push: error introspecting artifact \"centos-stream:8\": no candidates for version \"8\" and variant \"GenericCloud\" found" name=centos-stream version=8
time="2023-04-11T02:06:49Z" level=info msg="Writing results file"
time="2023-04-11T02:06:49Z" level=warning msg="artifact centos-stream:8 failed in stage push: error introspecting artifact \"centos-stream:8\": no candidates for version \"8\" and variant \"GenericCloud\" found"
time="2023-04-11T02:06:50Z" level=error msg="artifact centos-stream:8 failed in stage push: error introspecting artifact \"centos-stream:8\": no candidates for version \"8\" and variant \"GenericCloud\" found" name=centos-stream version=8
time="2023-04-11T02:06:50Z" level=info msg="Writing results file"
time="2023-04-11T02:06:50Z" level=fatal msg="artifact centos-stream:8 failed in stage push: error introspecting artifact \"centos-stream:8\": no candidates for version \"8\" and variant \"GenericCloud\" found"
```

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- KubeVirt version (use `virtctl version`):
- Kubernetes version (use `kubectl version`):
- common-templates version:
- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by lyarwood** [comment]
```
$ curl https://cloud.centos.org/centos/8-stream/x86_64/images/CHECKSUM
$
```

https://pagure.io/centos-infra/issue/1128

**Comment by lyarwood** [comment]
https://bugzilla.redhat.com/show_bug.cgi?id=2186258

**Comment by lyarwood** [comment]
https://cloud.centos.org/centos/8-stream/x86_64/images/CHECKSUM.asc is present (missing for 9) but that would mean carrying additional code to validate the signature etc. Might be worth it in the long run.

**Comment by 0xFelix** [comment]
Thanks for taking care of it @lyarwood.

It looks like the CHECKSUM file is back?

https://prow.ci.kubevirt.io/job-history/gs/kubevirt-prow/logs/periodic-containerdisks-push-nightly
